CREATE DATABASE APP;
USE APP;
CREATE TABLE users(idUser INT NOT NULL AUTO_INCREMENT,  username VARCHAR(16) NOT NULL,  email VARCHAR(255) NULL,  password VARCHAR(32) NOT NULL, create_time  NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (idUser));